<?php

/**
 * This file was automatically generated by the MakeFormRequest / make:form-req command.
 * You can modify this file.
 */
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProjectRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'name' => 'string|max:255|required',
            'laravel_version' => 'nullable|in:12.x,11.x,10.x',
            'database' => 'nullable|in:mysql,pgsql,sqlite,sqlsrv',
            'description' => 'nullable|string',

            'feature_id' => 'nullable|array',
            'feature_id.*' => 'exists:features,id',
        ];
    }

    public function messages()
    {
        return [
            'name.string' => 'name must be a string.',
            'name.max' => 'name may not be greater than 255 characters.',
            'name.required' => 'name is required.',
            'laravel_version.in' => 'The selected laravel_version is invalid.',
            'database.in' => 'The selected database is invalid.',
            'description.string' => 'description must be a string.',

            'feature_id.array' => 'feature_id must be an array.',
            'feature_id.*.exists' => 'The selected feature_id is invalid.',
        ];
    }
}
