<?php

/**
 * This file was automatically generated by the MakeFormRequest / make:form-req command.
 * You can modify this file.
 */

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProjectHasFeatureRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'feature_id' => 'integer|required|exists:features,id',
            'description' => 'string',
        ];
    }

    public function messages()
    {
        return [
            'feature_id.integer' => 'feature_id must be an integer.',
            'feature_id.required' => 'feature_id is required.',
            'feature_id.exists' => 'The selected feature_id is invalid.',
            'description.string' => 'description must be a string.',
        ];
    }
}
